#!/usr/bin/env python3

import os
import sys

import helpers
from analyzer import Analyzer
from termcolor import colored

def main():
    # ensure proper usage
    if len(sys.argv) != 2:
        sys.exit("Usage: ./tweet username")

    # absolute paths to lists
    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")

    # instantiate analyzer
    analyzer = Analyzer(positives, negatives)

    screen_name = sys.argv[1]
    # queries Twitter's API for user's most recent 50 tweets
    tweets = helpers.get_user_timeline(screen_name, 50)

    # if screen_name doesn't exist, return error
    if tweets == None:
        sys.exit("User is private or doesn't exist")

    # if screen_name exist, analyze each tweet and output it
    for tweet in tweets:
        # analyze word
        score = analyzer.analyze(tweet)
        if score > 0.0:
            print(colored(":)"+tweet, "green"))
        elif score < 0.0:
            print(colored(":("+tweet, "red"))
        else:
            print(colored(":|"+tweet, "yellow"))

if __name__ == "__main__":
    main()